### ISSUE TITLE
Throttling and request origin validation

### ISSUE THREAD

**Issue by pietvanzoen** [pietvanzoen/discussie#12]
Ideally we want to ensure that only the site sending the plusfries can trigger a valid plus on that site. I.e. example.com can add a plus for example.com. But a random curl request can’t add a plus to example.com. 

Not sure what the solution is here. 

@Keepitterron any thoughts? No rush. :)

**Comment by pietvanzoen** [comment]
Somewhat related do we want to prevent people from spamming the button? I do like how this kudos thing works: https://dcurt.is/bourdain-on-people

**Comment by keepitterron** [comment]
Agreed. I'd be fine with allowing a curl request to get the fries for a domain, but only that domain should be able to post. It makes a lot of sense.

For the throttling yeah, as it is I'm sure people would spam just out of curiosity or boredom, I like the clapping on medium that keeps increasing as you hold mouse down but I do not understand its purpose :/
At least disabling clicking once you've voted should be in order.

**Comment by pietvanzoen** [comment]
Lol... sorry. Didn't realize this was on completely the wrong repo.
